// Code generated by MockGen. DO NOT EDIT.
// Source: instruction_persistence.go

// Package mock_receipt is a generated GoMock package.
package mock_receipt

import (
	reflect "reflect"
	receipt "restservice/domain/receipt"

	gomock "github.com/golang/mock/gomock"
)

// MockInstructionRepository is a mock of InstructionRepository interface.
type MockInstructionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInstructionRepositoryMockRecorder
}

// MockInstructionRepositoryMockRecorder is the mock recorder for MockInstructionRepository.
type MockInstructionRepositoryMockRecorder struct {
	mock *MockInstructionRepository
}

// NewMockInstructionRepository creates a new mock instance.
func NewMockInstructionRepository(ctrl *gomock.Controller) *MockInstructionRepository {
	mock := &MockInstructionRepository{ctrl: ctrl}
	mock.recorder = &MockInstructionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstructionRepository) EXPECT() *MockInstructionRepositoryMockRecorder {
	return m.recorder
}

// InsertInstruction mocks base method.
func (m *MockInstructionRepository) InsertInstruction(instruction receipt.Instruction) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertInstruction", instruction)
	ret0, _ := ret[0].(int)
	return ret0
}

// InsertInstruction indicates an expected call of InsertInstruction.
func (mr *MockInstructionRepositoryMockRecorder) InsertInstruction(instruction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertInstruction", reflect.TypeOf((*MockInstructionRepository)(nil).InsertInstruction), instruction)
}

// ReadInstructionsByDepositId mocks base method.
func (m *MockInstructionRepository) ReadInstructionsByDepositId(depositId int) []receipt.Instruction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadInstructionsByDepositId", depositId)
	ret0, _ := ret[0].([]receipt.Instruction)
	return ret0
}

// ReadInstructionsByDepositId indicates an expected call of ReadInstructionsByDepositId.
func (mr *MockInstructionRepositoryMockRecorder) ReadInstructionsByDepositId(depositId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadInstructionsByDepositId", reflect.TypeOf((*MockInstructionRepository)(nil).ReadInstructionsByDepositId), depositId)
}
