// Code generated by MockGen. DO NOT EDIT.
// Source: deposit_service.go

// Package mock_receipt is a generated GoMock package.
package mock_receipt

import (
	reflect "reflect"
	msg "restservice/msg"

	gomock "github.com/golang/mock/gomock"
)

// MockDepositService is a mock of DepositService interface.
type MockDepositService struct {
	ctrl     *gomock.Controller
	recorder *MockDepositServiceMockRecorder
}

// MockDepositServiceMockRecorder is the mock recorder for MockDepositService.
type MockDepositServiceMockRecorder struct {
	mock *MockDepositService
}

// NewMockDepositService creates a new mock instance.
func NewMockDepositService(ctrl *gomock.Controller) *MockDepositService {
	mock := &MockDepositService{ctrl: ctrl}
	mock.recorder = &MockDepositServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepositService) EXPECT() *MockDepositServiceMockRecorder {
	return m.recorder
}

// GetDepositReport mocks base method.
func (m *MockDepositService) GetDepositReport(id int) msg.Deposit {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepositReport", id)
	ret0, _ := ret[0].(msg.Deposit)
	return ret0
}

// GetDepositReport indicates an expected call of GetDepositReport.
func (mr *MockDepositServiceMockRecorder) GetDepositReport(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepositReport", reflect.TypeOf((*MockDepositService)(nil).GetDepositReport), id)
}

// GetOrCreateDeposit mocks base method.
func (m *MockDepositService) GetOrCreateDeposit(id, clientId, nominal int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateDeposit", id, clientId, nominal)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateDeposit indicates an expected call of GetOrCreateDeposit.
func (mr *MockDepositServiceMockRecorder) GetOrCreateDeposit(id, clientId, nominal interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateDeposit", reflect.TypeOf((*MockDepositService)(nil).GetOrCreateDeposit), id, clientId, nominal)
}
